name: Deploy to Vercel
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm install
      - run: npm run build
      - run: npx vercel@latest --prod --yes --scope unblockedgames --name typhelper
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
